# KNEEL and DeepKnee inference packages share the same docker image.
FROM miptmloulu/kneel:gpu

MAINTAINER Aleksei Tiulpin, University of Oulu, Version 1.0

RUN rm -rf /opt/pkg
RUN mkdir -p /opt/pkg/
COPY . /opt/pkg/
RUN pip install /opt/pkg/